### ISSUE TITLE
still errors

### ISSUE THREAD

**Issue by ty3232** [EricHu33/URP_SSR#1]
Hi wanted to use your ssr but I still have like 66 errors and don't know why most of them say 
![TinyTake25-11-2024-03-32-59](https://github.com/user-attachments/assets/eb371311-ea26-4b50-a1c6-fdf1604ef1b9)
'SSRTracePass' already defines a member called 'Execute' with the same parameter types

**Comment by EricHu33** [comment]
looks like the assembly definetion has confict in your project.

Also the path is a little weird. 

Tried export this repo's project into a unity package. 
![image](https://github.com/user-attachments/assets/a78014ce-dad1-49b5-974f-4c0906228359)

Then import the package to your existing project instead of drag the whole repo inside your exist project.

**Comment by ty3232** [comment]
Thanks it work fine
